apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cruder.fullname" . }}-config
  labels:
    {{- include "cruder.labels" . | nindent 4 }}
data:
  config.yaml: |
    server:
      port: 8080
      host: 0.0.0.0
      env: {{ .Values.appEnv }}
    database:
      host: {{ .Values.database.host }}
      port: {{ .Values.database.port }}
      user: {{ .Values.database.user }}
      dbname: {{ .Values.database.name }}
      sslmode: disable
    api:
      key: ""