apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cruder.fullname" . }}-secrets
  labels:
    {{- include "cruder.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-password: {{ .Values.database.password | quote }}
  api-key: {{ .Values.apiKey | quote }}