apiVersion: v1
kind: Secret
metadata:
  name: cruder-secrets
  namespace: default
  labels:
    app: cruder
type: Opaque
stringData:
  db-password: "{{ .Values.database.password }}"
  api-key: "{{ .Values.apiKey }}"