apiVersion: v1
kind: ServiceAccount
metadata:
  name: cruder
  namespace: default
  labels:
    app: cruder
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cruder
  namespace: default
  labels:
    app: cruder
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cruder
  namespace: default
  labels:
    app: cruder
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cruder
subjects:
- kind: ServiceAccount
  name: cruder
  namespace: default